# Generated by Django 3.2.8 on 2021-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='myphoto', upload_to='employeeprofile/images/')),
                ('email', models.EmailField(default='email@company.com', max_length=254)),
                ('password', models.CharField(default='password', max_length=10)),
                ('phone', models.CharField(default='1234567890', max_length=10)),
                ('address', models.CharField(default='home', max_length=20)),
            ],
        ),
    ]
