# Generated by Django 3.2.8 on 2021-10-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='home', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='email@company.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='password', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='1234567890', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='myphoto', upload_to='employeeprofile/images/'),
        ),
    ]
